name: docker_push

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push nginx
        uses: docker/build-push-action@v2
        with:
          context: ./nginx
          push: true
          tags: allieee/melodramatique:nginx
      -
        name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: allieee/melodramatique:frontend
      -
        name: Build and push search backend
        uses: docker/build-push-action@v2
        with:
          context: ./search/melodrama-search
          push: true
          tags: allieee/melodramatique:search

      -
        name: Build and push search db
        uses: docker/build-push-action@v2
        with:
          context: ./search/db
          push: true
          tags: allieee/melodramatique:db
